# Site settings
title: 程语
email: OakShell.sea@gmail.com
description: > 
  一些关于编程学习的记录
baseurl: /myblog # the subpath of your site, e.g. /blog
url: oakshell.github.io # the base hostname & protocol for your site
username:  OakShell

# Build settings
markdown: kramdown
highlighter: pygments
